name: Misty
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.12.2
  html: ^0.14.0+4
  geolocator: ^6.1.13
  path_provider: ^1.6.24
  cupertino_icons: ^1.0.0

dev_dependencies:
flutter:
  assets:
    - assets/icons/day/01d.png
    - assets/icons/day/02d.png
    - assets/icons/day/03d.png
    - assets/icons/day/04d.png
    - assets/icons/day/09d.png
    - assets/icons/day/10d.png
    - assets/icons/day/11d.png
    - assets/icons/day/13d.png
    - assets/icons/day/50d.png
  
    - assets/icons/night/01n.png
  uses-material-design: true
